# Generated by Django 3.2.12 on 2022-03-08 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220308_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temporary',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
